### ISSUE TITLE
figwheel REPL doesn't have auto-completion.

### ISSUE THREAD

**Issue by crocket** [malyn/figwheel-node-template#3]
How can I enable auto-completion in figwheel REPL?

**Comment by malyn** [comment]
[lein-figwheel](https://github.com/bhauman/lein-figwheel) doesn't support that at the moment.  I believe that you get close if you use [rlwrap](https://github.com/hanslub42/rlwrap) per [the docs on the lein-figwheel page](https://github.com/bhauman/lein-figwheel#using-the-clojurescript-repl) though.
